In [16]:
import numpy as np
a=np.array([1,2,3]) #list is the argument
b=np.array((1,2,3))#tuple is the argument(passing value)
print(a)
print(b)


[1 2 3]
[1 2 3]


In [17]:
c=np.array(([1,2,3],[4,5,6],[7,8,9]))
print(c)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
c[1]
print(c[1])

[4 5 6]


In [8]:
c[0]

array([1, 2, 3])

In [9]:
print(c[0])

[1 2 3]


In [10]:
print(c[0:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
c[0][1]

2

In [13]:
print(c[0][1:])

[2 3]


In [15]:
d=np.zeros((2,3))
print(d)

[[0. 0. 0.]
 [0. 0. 0.]]


In [17]:
a=np.arange(10,25,2)# its NOT arrange --ARANGE Parameter are first no. last no. and interval by which it should increase.
print(a)

[10 12 14 16 18 20 22 24]


In [19]:
b=np.linspace(5,6,10)#NOT Linespace its linspace Parameter first no. last no. and how many no. in between them.
print(b)

[5.         5.11111111 5.22222222 5.33333333 5.44444444 5.55555556
 5.66666667 5.77777778 5.88888889 6.        ]


In [26]:
c=np.full([3,4],9.8)# Parameter tuple and value to inserted. BM- list was to inspect whether it works or not.
print(c)

[[9.8 9.8 9.8 9.8]
 [9.8 9.8 9.8 9.8]
 [9.8 9.8 9.8 9.8]]


In [29]:
d=np.random.random([3,4])# BM- list was to inspect whether it works or not.
print(d)
print()
e=np.random.random((3,4))
print(e)

[[0.7319175  0.76017025 0.69354518 0.92019507]
 [0.55187075 0.66758643 0.61200372 0.0200259 ]
 [0.14800363 0.74452479 0.21876144 0.44214097]]

[[0.86321621 0.12040039 0.84800757 0.27797048]
 [0.1590969  0.82632616 0.8436394  0.48108196]
 [0.48654254 0.28913732 0.39362806 0.34007837]]


In [30]:
print(e.shape)
print(d.shape)

(3, 4)
(3, 4)


In [34]:
d.shape=(4,3) # Important feature
print(d)

[[0.7319175  0.76017025 0.69354518]
 [0.92019507 0.55187075 0.66758643]
 [0.61200372 0.0200259  0.14800363]
 [0.74452479 0.21876144 0.44214097]]


In [35]:
a=np.array(((1,2,3),(4,5,6)))
print(a)

[[1 2 3]
 [4 5 6]]


In [36]:
print(a.shape) #a.shape return the tuples
a.shape = (3,2)
print()
print(a)

(2, 3)

[[1 2]
 [3 4]
 [5 6]]


In [38]:
a=np.arange(20) # Range gives the no. from 0 to n-1
print(a)
print(a.size)# SIZE is new function

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
20


In [42]:
print(a.ndim)# gives the dimension of the array - 1d or 2D array

1


In [40]:
print(a.dtype) # returns the datatype of the element of the array.

int32


In [43]:
b=np.linspace(2,3,9)
print(b)
print(b.dtype)

[2.    2.125 2.25  2.375 2.5   2.625 2.75  2.875 3.   ]
float64


In [44]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.sum(a))

6


In [47]:
c=np.sum((a,b))
print(c)

21


In [46]:
print(np.subtract(a,b))

[-3 -3 -3]


In [50]:
print(np.sum((a,b),axis=0))

[5 7 9]


In [51]:
print(np.sum((a,b),axis=1))

[ 6 15]


In [54]:
print(np.exp(a))
print(np.cos(a))
print(np.sin(a))
print (a)

[ 2.71828183  7.3890561  20.08553692]
[ 0.54030231 -0.41614684 -0.9899925 ]
[0.84147098 0.90929743 0.14112001]
[1 2 3]


In [55]:
print(a,b)


[1 2 3] [4 5 6]


In [56]:
np.equal(a,b)

array([False, False, False])

In [60]:
a=np.array([[1,2,3],[4,5,6]]) # This is also called Broadcasting.
b=np.array([1,2,3])
print(np.sum((a,b)))


[[2 4 6]
 [5 7 9]]


In [5]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)
b=np.array([[0,9,8],[6,4,2]])
print(b)
print()
print(np.concatenate((a,b),axis=1))
print()
print(np.concatenate((a,b),axis=0))

[[1 2 3]
 [4 5 6]]
[[0 9 8]
 [6 4 2]]

[[1 2 3 0 9 8]
 [4 5 6 6 4 2]]

[[1 2 3]
 [4 5 6]
 [0 9 8]
 [6 4 2]]


In [11]:
a=np.array([[1,2,3],[4,5,6]])
print(np.stack((a,b),axis=0))
print()
print()
print()
print(np.stack((a,b),axis=1))

[[[1 2 3]
  [4 5 6]]

 [[0 9 8]
  [6 4 2]]]



[[[1 2 3]
  [0 9 8]]

 [[4 5 6]
  [6 4 2]]]


In [18]:
a=np.array([12,34,56])
print(np.stack(a))

[12 34 56]


In [27]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[10,20,30],[40,50,60]])
print(a)
print(b)
print("Vertical Stacking")
print(np.vstack((a,b)))
print("horizontal Stacking")
print(np.hstack((a,b)))
print("Horizontal Concatenating")
print((np.concatenate((a,b),axis=0)))
print("vertical COncetenating")
print((np.concatenate((a,b),axis=1)))
#horzontal stacking == vertical concatenaing and vise-versa      

[[1 2 3]
 [4 5 6]]
[[10 20 30]
 [40 50 60]]
Vertical Stacking
[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]
 [40 50 60]]
horizontal Stacking
[[ 1  2  3 10 20 30]
 [ 4  5  6 40 50 60]]
Horizontal Concatenating
[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]
 [40 50 60]]
vertical COncetenating
[[ 1  2  3 10 20 30]
 [ 4  5  6 40 50 60]]


In [8]:
#to check which is faster numpy or list.
import time as t
import numpy as np
def using_list():
    t1=t.time()
    x=np.arange(1000000)
    y=np.arange(1000000)
    z=[x[i]+y[i] for i in range(len(x))]
    return (t.time()-t1)
def using_npArray():
    t1=t.time()
    a=np.array(1000000)
    b=np.array(1000000)
    c=a+b
    return (t.time()-t1)
a=using_list()
b=using_npArray()
print(a,b)
#print("it is "+str(a/b)+"times faster")

0.2703235149383545 0.0


In [4]:
import numpy as np
xq=np.arange(20)
print(xq)
x1=np.arange(1,20)
print(x1)
x2=np.arange(1,20,0.5)
x2

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5,
       12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. , 16.5, 17. ,
       17.5, 18. , 18.5, 19. , 19.5])